pipeline {
    agent any
    // parameters { 

    //     string(
    //         name: 'RELEASE_DIR', 
    //         defaultValue: '/home/samples',
    //         description: 'sample'
    //         )

    //     // string(
    //     //     name: 'Time_out', 
    //     //     defaultValue: '11000',
    //     //     description: 'Time out in second for the job'
    //     //     )

	// }


    stages {
        stage('Clone sources') {
            steps {
				git branch: 'main',
                url: 'https://github.com/valerymo/misc.git'
            } 
        }

        stage('Build') {
            steps {
				sh "pwd"
				dir ('service-a')
				{
					sh "pwd"
					sh 'mvn clean install'
					sh "cd .."					
				}
            }
        }
    }
}
